services:

  discordbot:
    build:
      context: .
      network: host

    container_name: TGAS

    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - /mnt/nas/Pieter/2_discord_bot/TGAS/persistent_data:/app/persistent_data
    
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      WYNN_API_TOKEN: ${WYNN_API_TOKEN}
  