services:

  discordbot:
    build: .

    container_name: TGAS_bot

    restart: unless-stopped

    volumes:
      - /mnt/nas/Pieter/2_discord_bot/TGAS_bot/persistent_data:/app/persistent_data
    
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      WYNN_API_TOKEN: ${WYNN_API_TOKEN}
  